#!/usr/bin/env bash

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [ "$m" = "$MON_MIDDLE" ]; then
      MONITOR=$m polybar --reload -c ~/.config/polybar/config_DP.ini &
    elif [ "$m" = "$MON_INTERNAL" ]; then
      MONITOR=$m polybar --reload -c ~/.config/polybar/config_eDP.ini &
    fi
  done
else
  polybar --reload polybar -c ~/.config/polybar/config_eDP.ini &
fi
