#!/usr/bin/env bash

if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        if [ "$m" = "HDMI-0" ]; then
            MONITOR=$m polybar --reload -c ~/.config/polybar/config_HDMI_0 &
        elif [ "$m" = "eDP-1-2" ]; then
            MONITOR=$m polybar --reload -c ~/.config/polybar/config_eDP_1_2 &
        fi
    done
else
    polybar --reload polybar -c ~/.config/polybar/config_eDP_2 &
fi
